### ISSUE TITLE
ValueError: unknown url type: 'path/to/mlsd'

### ISSUE THREAD

**Issue by hujinhong** [Sonettoo/CRS-Diff#11]
Traceback (most recent call last):
  File "/data/hjh/CRS-Diff-main/CRS-Diff-main/src/test/test.py", line 34, in <module>
    apply_mlsd = MLSDdetector()
  File "/data/hjh/CRS-Diff-main/CRS-Diff-main/./annotator/mlsd/__init__.py", line 22, in __init__
    load_file_from_url(remote_model_path, model_dir=annotator_ckpts_path)
  File "/home/user/miniconda3/envs/llava/lib/python3.10/site-packages/basicsr/utils/download_util.py", line 98, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "/home/user/miniconda3/envs/llava/lib/python3.10/site-packages/torch/hub.py", line 621, in download_url_to_file
    req = Request(url, headers={"User-Agent": "torch.hub"})
  File "/home/user/miniconda3/envs/llava/lib/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/home/user/miniconda3/envs/llava/lib/python3.10/urllib/request.py", line 348, in full_url
    self._parse()
  File "/home/user/miniconda3/envs/llava/lib/python3.10/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'path/to/mlsd'

**Comment by PuKuang** [comment]
I had the same issue. And it seems like the released test code is not complete, and it lasks some pth files?

**Comment by Sonettoo** [comment]
Hi, test.py needs all the weights of the conditional extractor, you can get them via [uni-controlnet](https://github.com/ShihaoZhaoZSH/Uni-ControlNet/tree/main) or you can choose to quickstart via [python src/test/inference.py](https://github.com/Sonettoo/CRS-Diff/blob/main/src/test/inference.py).
